### ISSUE TITLE
Proposal: Remove memguard

### ISSUE THREAD

**Issue by jonnystoten** [openpubkey/openpubkey#103]
I'd like to propose that we remove memguard from OpenPubkey.

Some background to why we added memguard can be found in the original issues #11 and #47. The PR that added it is #48. I added [a comment to that PR](https://github.com/openpubkey/openpubkey/pull/48#issuecomment-1803552330) with some thoughts which I can expand on here.

I think there are three issues with the implementation:

## Lack of complete protection

Memguard does two things for us:

1. Provides a function to wipe byte slices, which we can use to remove secrets from memory.
2. Provides a LockedBuffer type which prevents the contents in memory being swapped to disk.

I think the wiping byte slices is a reasonable idea, but the LockedBuffer is more problematic. If we need to pass the underlying bytes from a LockedBuffer to a library function (in the stdlib or a dependency) and that function copies the bytes, we lose the protection that the LockedBuffer is giving us. This kind of thing is very difficult to keep track of - any upgrade to a dependency or the stdlib could introduce some copying without us noticing unless we're auditing the code. For the stdlib this is even more difficult because the version of Go that an application using OpenPubkey is built with determines the version of the stdlib.

Some places where this happens are documented in #51, #52, and #53. This may not be exhaustive!

I think at the end of the day, Go isn't really suited to this sort of manual memory management.

## Leaky abstraction

The way memguard needs to be used means that the OIDC client interface needs to know about memguard, which is slightly cumbersome for implementers.

This isn't the end of the world, and I do think that this added complexity of the implementation could be worth it if the result was totally bulletproof, but as it doesn't fully prevent secrets being swapped etc, I don't think the juice is worth the squeeze.

## Issues debugging

I've also ran into issues debugging the code with VS Code which I think is down to https://github.com/awnumar/memguard/issues/150.

# Other things to note

This would be a breaking change as memguard forms part of the public-facing interface as noted above. We should make a decision on whether to do this before we release v1.0.

/cc @mrjoelkamp @EthanHeilman

**Comment by EthanHeilman** [comment]
I think about our use of memguard LockedBuffers as consisting of two things:
* LockedBuffers in the client
* LockedBuffers in the GQ signature library

## LockedBuffers in the client and provider
In the client and provider we used a LockedBuffer to protect the ID Token RSA signature when we are computing a GQ signature. 

This use of LockedBuffer in the client is not a useful as we would like it:
*  It adds a small but real complexity to implementing new OpenID Providers,
*  It is only needed for the GQ Signature setting, there is no security need for ID Tokens we don't want to transform into GQ signatures.
* Since the ID Token's RSA signature is sent over the wire, lots of code handles it before it is placed in a LockedBuffer it does not provide complete protection. Github which the current OP where the LockedBuffer helps security has the ID Token read by http.Client-->json.Marshall and then is placed in the LockedBuffer.

I do believe in the github setting, the LockedBuffer does provide a real improvement in security, as it makes it less likely that our code will leak the ID Token RSA signature.

I see three paths we can go with this:
1. Remove LockedBuffer from the client.
2. Remove LockedBuffer from the client and find a different way to protect the RSA signature. For instance if we moved GQ Signature creation into the provider we don't have to expose the protection mechanism outside the provider. I talk about this below.
3. Modify http.Client and json.Marshall to use LockedBuffer internally. I'm not sure how simple of change this would be or if existing libraries exist that do this.
4. Keep things as they are.

The advantage of 1 is that it is simple. 2 is a biggest change that 1, but I lean towards 2 because I think it moves us in the right architecture direction and has no security impact.

### GQ Signature computation in the client

All providers would then be GQ Providers or not GQ Providers. You would have GoogleOp (no GQ) and GoogleOpGq (GQ), by selecting which Op to use, you would also be selecting if you wanted GQ signatures or not.

I'm favorable to this approach because:
1. It makes OpenPubkey very flexible. If we wanted to add zkLogin style snark signatures #101 or gitlab GQ  CIC attestations #100  this would provide an excellent way place to add that. 
2. Verifiers are already handling CIC verification and extraction based on provider specific details. For instance githubOp knows that CIC is in the aud rather than the 
3. We have providers like githubOp where we already require the signature always be GQ.
4. It lets provider implementations choose how they want to protect their secrets.


### LockedBuffers in the GQ signature library

LockedBuffers are used internally to ensure we that after signing is completely we don't leak any secret state. The complexity cost to anyone outside of the GQ internals is very low and we do get a minor but real security benefit. I could be convinced otherwise but I don't see a reason to remove memguard in the GQ signature library

**Comment by EthanHeilman** [comment]
Closing as this PR resolves this issue but making memguard internal to OpenIdProvider. Memguard is no longer a leaky abstraction in our model
https://github.com/openpubkey/openpubkey/pull/122
